#!/usr/bin/env bash
while read p; do
    if [[ $p == *"APP_ENV"* ]]
    then
      export $p
    fi
done <.env

timestamp() {
  date +"_%s"
}

opening () {
    RED='\033[0;31m'
    NC='\033[0m' # No Color
    echo -e "${RED}"
    echo "**************************************************"
    echo "Dinner Menu"
    echo " $1"
    echo "**************************************************"
    echo -e "${NC}"
}

documentation () {
   RED='\033[0;31m'
   NC='\033[0m' # No Color
   echo -e "${RED}"
   echo "**************************************************"
   echo "* $1"
   echo "**************************************************"
   echo -e "${NC}"
}


opening "Updating Application - $APP_ENV"
documentation "Beginning update; git status"

git status
documentation "Putting Laravel in maintenance mode"
php artisan down

if [[ $APP_ENV != "local" ]]
then
    documentation "Clear cache, config & routes"
    rm bootstrap/cache/config.php
    php artisan cache:clear
    php artisan config:clear
    php artisan route:clear
fi

documentation "Checkout branch and pull code"
git stash
git checkout main
git pull origin main


documentation "Install Composer packages"
export  COMPOSER_ALLOW_SUPERUSER=1
composer install --optimize-autoloader

documentation "Run database migrations"

php -d memory_limit=-1 artisan migrate

documentation "Dump composer autoload & clear compiled classes"
composer dump-autoload -o
php artisan clear-compiled

documentation "Setting git tag"
directory=${PWD##*/}
git tag "$APP_ENV$(timestamp)" HEAD -f
git push origin --tags -f

documentation "Clear and cache cache, config & routes"
rm bootstrap/cache/config.php
php artisan cache:clear
php artisan config:clear
php artisan route:clear

php artisan config:cache
php artisan route:cache

documentation "Restarting queuing service"

php artisan queue:restart


documentation "Building Frontend"
cd frontend
npm install
npm run build
cd ../

documentation "Updating permissions"

chmod -R 775 .
chown -R www-data:www-data .

chmod -R 777 storage/ bootstrap/cache
chown -R www-data:www-data storage/ bootstrap/cache

documentation "Taking Laravel out of maintenance mode."
php artisan up

echo ""
echo ""


